version: "3"
services:
    p4a:
        image: p4apy3
        volumes:
            - .:/home/user/hostcwd
        # entrypoint: ". venv/bin/activate; bash"
        entrypoint: venv/bin/p4a
        # command: /bin/bash


